language: python

python:
    - 2.7
env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk

install:
  - pip install $TWISTED
  - pip install -r requirements.txt

script:
  - trial lisa/plugins/chatterbot

notifications:
  irc: "irc.oftc.net#lisa"

branches:
  only:
    - master

